language: go

os:
  - linux
  - osx
  - windows

go:
  - tip
  - 1.12
  - 1.11

install:
  - mkdir ./testdata/output

script: env GO111MODULE=on go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success: bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
